apiVersion: v1
kind: Service
metadata:
  name: ollama-chat
  namespace: itti
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.iad.aaaaaaaajm3cqhlbfdy4d2b4bc65sighbs7w4wzz4ke7xpxjnn4al72tuteq"
spec:
  type: LoadBalancer
  selector:
    app: ollama-chat
  ports:
    - port: 3000 
      targetPort: 3000
