apiVersion: v1
kind: Service
metadata:
  name: ollama-chat
  namespace: itti
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.us-chicago-1.aaaaaaaarwhvwkr5mvxpmvmgn4bdlvu3jhzmfcpxuy3rhccxoriee6nilvca"
spec:
  type: LoadBalancer
  selector:
    app: ollama-chat
  ports:
    - port: 3000 
      targetPort: 3000
