apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
  namespace: itti
  labels:
    app: ollama
spec:
  serviceName: "ollama"
  replicas: 2
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: name
                operator: In
                values:
                - poolgpu
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule" 
      containers:
      - name: ollama
        image: ord.ocir.io/ax0yupcusky2/repo/ollama:latest
        ports:
        - containerPort: 11434
        volumeMounts:
        - name: ollama-storage
          mountPath: /root/.ollama
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Starting Ollama server..."
            ollama serve &
            echo "Waiting for server to be ready..."
            sleep 10
            echo "Pulling models..."
            ollama pull gemma3:1b
            ollama pull llama3.2:3b
            ollama pull gpt-oss:20b
            echo "All models are ready. Keeping Ollama running..."
            tail -f /dev/null
      imagePullSecrets:
      - name: ocir
      
  volumeClaimTemplates:
  - metadata:
      name: ollama-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: sc-ollama
      resources:
        requests:
          storage: 200Gi

