apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ollama
  namespace: itti 
spec:
  storageClassName: "sc-ollama"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
